version: '3.8'
services:
  py-service-api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - '8006:8000'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./api/src/alembic/versions:/app/src/alembic/versions
